version: '3.1'

services: 

  localstack:
    image: localstack/localstack:latest
    environment: 
      - AWS_DEFAULT_REGION=ap-southeast-2
      - EDGE_PORT=4566
      - SERVICES=dynamo,apigateway,lambda
      - PERSISTENCE=1
    ports: 
      - '4566-4583:4566-4583'
    volumes:
      - ./localstack/bootstrap:/opt/bootstrap/
      - ./data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
